###
GET {{url}}/worlds/list
Authorization: Bearer {{token}}

###
POST {{url}}/worlds/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "test",
  "properties": "{'a': 1, 'b': 2}",
  "allowList": "['a', 'b']"
}

###
POST {{url}}/worlds/upload/1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="world"; filename="example.zip"

< ./example.zip

###
GET {{url}}/servers/list/1
Authorization: Bearer {{token}}

###
POST {{url}}/servers/get
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "worldId": 1,
  "version": "1.20.51.01"
}

###
POST {{url}}/servers/use
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "worldId": 1,
  "serverId": 2
}

###
DELETE {{url}}/servers/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "worldId": 1,
  "serverId": 1
}

###
GET {{url}}/backups/list/1
Authorization: Bearer {{token}}

###
POST {{url}}/backups/backup
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "worldId": 1,
  "name": ""
}

###
POST {{url}}/backups/restore
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "worldId": 1,
  "backupId": 1,
  "ifBackup": true
}

###
DELETE {{url}}/backups/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "worldId": 1,
  "backupId": 3
}


